# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9493d5ca77f5019f5f9661a4fcf48391995aea83a3bfbcc7f8d607e09ce980d3d00302addaa5ba70de8a4843bd58b0803557d8aac0757566f5f6f430e00d9ecf

test:
  secret_key_base: ec5bcaa8b22b2f6af632699c299af253f9ff0983f80526ae742766b43c99e988975c008e7c5ec9350d1fb7e1a64be12102e1cbeca10a9a28badeeafcc55ee819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
